### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by bhaskarmelkani** [jordanpapaleo/js-helpers#1]
Hey,

I have written some utilities in the following repo, may we can merge some them in your repo.
https://github.com/bhaskarmelkani/web-utils

Let me know.

Thanks :)

**Comment by jordanpapaleo** [comment]
That would be awesome!!!

Sent from my smallest computer

On Feb 4, 2017, at 3:40 PM, Bhaskar Melkani <notifications@github.com> wrote:

Hey,

I have written some utilities in the following repo, may we can merge some them in your repo.
https://github.com/bhaskarmelkani/web-utils

Let me know.

Thanks :)

**Comment by bhaskarmelkani** [comment]
Let me know, how can we move forward with it.?

**Comment by jordanpapaleo** [comment]
Create a pull request please
